name: OTEL Action Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  job1:
    name: Random Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Do some random work
        run: sleep $[$RANDOM % 10].$[$RANDOM % 10]s

  job2:
    name: Random Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Do some random work
        run: sleep $[$RANDOM % 10].$[$RANDOM % 10]s

  test-action:
    name: Test OTEL action
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
      - name: Run otel-action
        uses: ./
        with:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          HEADERS: ${{ secrets.HEADERS }}
          SERVICE_NAME: "otel-action"
          VERSION: "pr-5"
